# Generated by Django 5.0.4 on 2024-04-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('cantidad_habitaciones', models.PositiveIntegerField()),
                ('telefono_hotel', models.CharField(max_length=15)),
                ('correo_hotel', models.EmailField(max_length=254)),
                ('descripcion_hotel', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'hotel',
                'ordering': ['id'],
            },
        ),
    ]
