# Generated by Django 5.0.4 on 2024-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicio_tiposervicio_hotel_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='nombre',
            field=models.TextField(max_length=100),
        ),
    ]
