# Generated by Django 5.0.4 on 2024-04-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tiposervicio_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='tipo_servicio',
        ),
    ]
