# Generated by Django 5.0.4 on 2024-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_habitacion_serviciohabtacion_tipohabitacion_reserva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='servicio',
        ),
        migrations.AddField(
            model_name='hotel',
            name='servicios',
            field=models.ManyToManyField(related_name='hoteles', to='core.servicio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios_extra',
            field=models.ManyToManyField(related_name='reservas', to='core.servicio'),
        ),
    ]
