# Generated by Django 5.0.4 on 2024-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_hotel_servicio_hotel_servicios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicios_extra',
        ),
    ]
