# Generated by Django 5.0.4 on 2024-04-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_reserva_servicios_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicios_extra',
            field=models.ManyToManyField(related_name='reservas', to='core.servicio'),
        ),
    ]
