# Generated by Django 5.0.4 on 2024-04-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_estadoreserva_reserva_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
